package com.ge.rfr.auth;

public interface Privileges {

    String RFR_ADMIN = "RFR_ADMIN";
    String RFR_INSTALLATION_DIRECTOR = "RFR_INSTALLATION_DIRECTOR";
    String RFR_TIM = "RFR_TIM";
    String RFR_TEAM_MEMBER = "RFR_TEAM_MEMBER";
    String WORKFLOW_CREATE = "ROLE_WORKFLOW_CREATE";
    String WORKFLOW_VIEW = "ROLE_WORKFLOW_VIEW";
    String WORKFLOW_DISABLE = "ROLE_WORKFLOW_DISABLE";
    String PHONE_CALL_CREATE = "ROLE_PHONE_CALL_CREATE";
    String PHONE_CALL_VIEW = "ROLE_PHONE_CALL_VIEW";
    String ACTION_ITEM_CREATE = "ROLE_ACTION_ITEM_CREATE";
    String ACTION_ITEM_VIEW = "ROLE_ACTION_ITEM_VIEW";

}
